version: '3.4'

services:
  articlechat:
    image: article-chat
    build:
      context: ./backend_experiment
      dockerfile: ./Dockerfile
    environment:
      # A JSON with 'username' and 'password' keys
      PGVECTOR_CREDENTIALS: ${PGVECTOR_CREDENTIALS}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA:-public}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      COGNITO_REGION: ${COGNITO_REGION}
      COGNITO_POOL_ID: ${COGNITO_POOL_ID}
      COGNITO_APP_CLIENT_ID: ${COGNITO_APP_CLIENT_ID}
      COGNITO_CLIENT_SECRET: ${COGNITO_CLIENT_SECRET}
      COGNITO_DOMAIN: ${COGNITO_DOMAIN}
      COGNITO_REDIRECT_URL: ${COGNITO_REDIRECT_URL}
      COGNITO_TOKEN_URL: ${COGNITO_TOKEN_URL}
      DEPLOYMENT_DOMAIN: ${DEPLOYMENT_DOMAIN}

    ports:
      - 80:80

  database:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    
volumes:
  data:
