version: '3.4'

services:
  articlechat:
    image: article-chat
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA:-public}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      COGNITO_REGION: ${COGNITO_REGION}
      COGNITO_POOL_ID: ${COGNITO_POOL_ID}
    ports:
      - 8000:8000

  database:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    
volumes:
  data:
