version: '3.4'

services:
  articlechat:
    image: article-chat
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install -r requirements-dev.txt && python -m uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"]
    volumes:
      - ./backend:/app
    env_file:
      - .env
    ports:
      - 80:80

  database:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    
volumes:
  data:
