# Inspired by https://betterprogramming.pub/deploy-a-cost-effective-vue-js-web-app-on-aws-with-terraform-and-github-actions-f84fb8df6d17

name: Deploy to S3 and Cloudfront

on:
  push:
    branches:
      - "master"
    paths:
      - 'frontend/**'

jobs:
  webapp:
    name:  Deploy webapp to Cloudfront
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup node.js environment
      uses: actions/setup-node@v3
    - name: Install dependencies and build
      working-directory: ./frontend
      env:
        VITE_APP_BACKEND_URL: https://api.journalarticle.chat
      run: |
        npm install
        npm run build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Deploy static site to S3 bucket
      working-directory: ./frontend
      run: aws s3 sync ./dist/ s3://${{ vars.AWS_BUCKET_NAME }} --delete
    
    - name: Invalidate CloudFront
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ARN }}
        PATHS: "/*"
        AWS_REGION: ${{ vars.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
